spring.application.name=ApiGateway


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

server.port=8090

spring.cloud.gateway.server.webflux.routes[0].id=department-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://department-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/departments/**



spring.cloud.gateway.server.webflux.routes[1].id=employee-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://employee-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/employees/**


