apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: employee-service

  template:
    metadata:
      labels:
        app: employee-service

    spec:
      containers:
        - name: employee-service
          image: employee-service:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: SERVER_PORT
              value: "8081"

            - name: SPRING_APPLICATION_NAME
              value: "EMPLOYEE-SERVICE"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:3306/employeedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"

            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"

            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"

            - name: EUREKA_INSTANCE_HOSTNAME
              value: "employee-service"

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"

            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "employee-service:8081"

---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: microservices

spec:
  selector:
    app: employee-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081

  type: ClusterIP